// World 1: Angkor Jungle Temples (GDD 6.2). Pacing: teach (1-3),
// combine (4-6), twist (7-8), master (9-10).
// Every level carries a `solution` that tests replay from a fresh start.

export const ANGKOR = [
  {
    id: '1-1',
    name: 'Root Gate',
    idea: 'Walking, digging earth, collecting gems',
    quota: 12,
    par: 70,
    map: [
      'WWWWWWWWWWW',
      'WH..G.G.G.W',
      'WWWWWWBWWEW',
      'W.GEEEEEEEW',
      'W.WWWWEWWWW',
      'W.EEEEEEEEW',
      'WGEGEEGEEGW',
      'WEEEEEEEEEW',
      'WEEGEEGEEGW',
      'WEEEEEEEEEW',
      'WWWWEEEWWWW',
      'W..G...G..W',
      'W..WW.WWCWW',
      'WG.G..WW*WW',
      'WWWWWXWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Swipe, use the D-pad or arrow keys to walk' },
      { x: 9, y: 2, text: 'Walk into earth to dig through it' },
      { x: 5, y: 3, text: 'Rocks fall when nothing holds them up' },
      { x: 5, y: 13, text: 'The exit gate opens once you reach the gem quota' },
      { x: 8, y: 11, text: 'A cracked wall... a hammer could open it later' },
    ],
    solution: 'RRRRRRRRDDLLLLLLLLDDDRRRRRRRRDDLLLLLLDRDRDLLRRRRLLDDLLLLRRRRD',
  },
  {
    id: '1-2',
    name: 'Falling Stones',
    idea: 'Gravity and the wobble warning',
    quota: 14,
    par: 90,
    map: [
      'WWWWWWWWWWW',
      'WH.EEEEEEEW',
      'W.EBEEBEBEW',
      'W.EGEEGEGEW',
      'W.EEBEEEEEW',
      'WEBEGEEBEBW',
      'WEGEEEBEGGW',
      'WEEBEEGEEEW',
      'WEEGEBEEBEW',
      'WEBEEGEEGEW',
      'WEGEEEEEEEW',
      'WWWWEEEWWWW',
      'W....P..F*W',
      'WEBEEBEEBEW',
      'WEGEEGEEGEW',
      'WWWWWXWWWWW',
    ],
    tips: [
      { x: 2, y: 2, text: 'A rock wobbles for a moment before it falls' },
      { x: 3, y: 3, text: 'Standing right under a rock is safe. Only a falling rock hurts' },
      { x: 5, y: 12, text: 'Touch an idol to save a checkpoint' },
    ],
    solution: 'DDRRRRRRRDDDRDDDLLUULLUULDLLDDRDRRDLLLLUURRDRDDDRRDDRRRUUDLLULLLLLLDDRRRRD',
  },
  {
    id: '1-3',
    name: 'Hall of Faces',
    idea: 'The hammer: smash cracked walls',
    quota: 16,
    par: 95,
    map: [
      'WWWWWWWWWWW',
      'WH..G.G.hGW',
      'WWWWWWWWWCW',
      'WG.....E..W',
      'WWCWWCWEWWW',
      'WG.WGGWE.GW',
      'WGGWGGWEBEW',
      'WWWWWWWEEGW',
      'WG.C..E.EEW',
      'WGWWWWEWWCW',
      'WGG.BGE.W*W',
      'WWWWWWEWWWW',
      'W....PE...W',
      'W.WCWWWWW.W',
      'W.WGGGGGW.W',
      'W.WWWWWWW.W',
      'W....X....W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 8, y: 1, text: 'A hammer! Face a cracked wall and press the tool button (Space)' },
      { x: 9, y: 1, text: 'Cracked walls show hairline fractures' },
    ],
    solution: 'RRRRRRRRdTDDLLLLLLLLRdTDDLDRUUURRRdTDDDLURUURRDDRRDDDdTDDUULLLLLlTLLLDDRRLLUURRRRRDDLRDDLLLdTDDRRRRLLLLUULLDDDDRRRR',
  },
  {
    id: '1-4',
    name: 'Serpent Steps',
    idea: 'Temple snakes: crush them with falling rocks',
    quota: 12,
    par: 80,
    secretExit: 'S1',
    map: [
      'WWWWWWWWWWW',
      'WH.G..G..GW',
      'WWWWWWWWWEW',
      'WG..B..B.EW',
      'WWWWC.WC.EW',
      'W.G..S..G.W',
      'W.WWOWWOWWW',
      'W.EEGEBEEGW',
      'WEEGEEEEGEW',
      'WWWWWW.WW.W',
      'W.GS....G.W',
      'WFWWW.OWWFW',
      'W*WW....WYW',
      'WW.....WWWW',
      'WWWGGXGGWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 8, y: 4, text: 'Snakes block narrow halls. Smash the cracked floor to drop the boulder on one' },
      { x: 9, y: 9, text: 'Snakes move every other beat. Time your crossing' },
    ],
    solution: 'RRRRRRRRDDDL..........lT.....DUULLLDlT...ULLLLRRRRDDLLLLDDRRRDLRRRR....URRDLRDDLRLLLLLLLLDDUURRRRDDDLLDRURRDRLL',
    secretSolution: 'RRRRRRRRDDDL..........lT.....DUULLLDlT...ULLLLRRRRDDLLLLDDRRRDLRRRR....URRDLRDDDD',
  },
  {
    id: '1-5',
    name: 'Monkey Business',
    idea: 'The stone monkey thief',
    quota: 8,
    par: 70,
    map: [
      'WWWWWWWWWWW',
      'WH.G.B.GG.W',
      'WWWWEEEWW.W',
      'W.........W',
      'W.WWWWWFW.W',
      'W.WWWWW*W.W',
      'W....M....W',
      'WWWWWWWWWEW',
      'WG.G.G.GGEW',
      'WEEEEEEEEEW',
      'W....X....W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 4, y: 1, text: 'Stone monkeys steal a gem and run. Corner one to get it back' },
      { x: 5, y: 2, text: 'A ring lets a thief run forever. Seal it with a falling rock' },
    ],
    solution: 'RRRDRDLL..LLDDDRRRRRRRRUUULLDDUURRUULLRRDDDDDDDLLLLLLLLDRRRRD',
  },
  {
    id: '1-6',
    name: 'Scarab Crossing',
    idea: 'Pits: fill them with rocks',
    quota: 9,
    par: 75,
    map: [
      'WWWWWWWWWWW',
      'WH.BO..BOGW',
      'WWWWWWWWWEW',
      'W..G...G..W',
      'W.WWWCWWW.W',
      'W.WGGGGGW.W',
      'W.WWWWWWW.W',
      'W....A....W',
      'WEWWWWWWWWW',
      'W.BO.BO..FW',
      'WWWWWWW.W*W',
      'WX.G.G.G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Push a boulder: walk into it. It is heavy, so you lean in first' },
      { x: 5, y: 1, text: 'Rocks pushed into a pit fill it and make new floor' },
      { x: 9, y: 3, text: 'Scarabs hug the wall on their left. Watch their loop' },
    ],
    solution: 'RRRRRRRRRRDDLLLLdTDDLLRRRRLLUULLLLDDDDDDRRRRRRRRRRDULLDDLLLLLL',
  },
  {
    id: '1-7',
    name: 'The Rolling Court',
    idea: 'Round stones roll off round things',
    quota: 9,
    par: 80,
    map: [
      'WWWWWWWWWWW',
      'WH..ERE..GW',
      'WWW..B..WEW',
      'WWW.BWB.WEW',
      'WWW.WWW.WEW',
      'WWW.WWWWWEW',
      'WG.O.....GW',
      'WWWWW.WWWWW',
      'W..ER.RE.GW',
      'W.GEGGGE.EW',
      'WEWWWEWWWEW',
      'WE.G.E.GFEW',
      'WEWWWWWW*EW',
      'W....X....W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 3, y: 1, text: 'Round stones roll off boulders, gems and other stones. Left first, then right' },
      { x: 5, y: 7, text: 'Gems are round too. Stones sitting on them will roll' },
    ],
    solution: 'RRRL........RRRRRRDDDDDLLLLLLLLRRRRDDDDDLLLLUURRRRRRRURDDDLDULRRDDLLLL',
  },
  {
    id: '1-8',
    name: 'Spike Garden',
    idea: 'Timed spike floors',
    quota: 10,
    par: 85,
    secretExit: 'S2',
    legend: {
      '1': { floor: 'spikes', meta: { period: 4, offset: 1 } },
      '2': { floor: 'spikes', meta: { period: 4, offset: 2 } },
      '3': { floor: 'spikes', meta: { period: 4, offset: 3 } },
      g: { floor: 'spikes', meta: { period: 4, offset: 0 }, obj: { t: 'gem' } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH.321^.G.W',
      'WWWWWWWWWEW',
      'WG.^G^G^..W',
      'WEWWWWWWWWW',
      'W.B^2^2^O.W',
      'WWWWWWWWW.W',
      'W.gGgGgGg.W',
      'WFFWWWWWW.W',
      'WY*WWWWWWXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Spikes peek out one beat before they strike. Walk with the wave' },
      { x: 1, y: 5, text: 'Push the boulder across. Leaning takes a beat, so read the rhythm' },
    ],
    solution: 'RRRRRRRRDDLLLLLLLLDDRRRRRRRRRRRRRRDDLL.LLLLLDDUURRRRRRRDD',
    secretSolution: 'RRRRRRRRDDLLLLLLLLDDRRRRRRRRRRRRRRDDLL.LLLLLLDD',
  },
  {
    id: '1-9',
    name: 'Keys of the Apsara',
    idea: 'Coloured keys and doors',
    quota: 9,
    par: 95,
    legend: {
      a: { obj: { t: 'key', color: 'gold' } },
      b: { obj: { t: 'key', color: 'green' } },
      v: { obj: { t: 'key', color: 'violet' } },
      J: { floor: 'door', meta: { color: 'gold' } },
      Q: { floor: 'door', meta: { color: 'green' } },
      V: { floor: 'door', meta: { color: 'violet' } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH.K..G..GW',
      'WWWWWWWWWDW',
      'W.a.......W',
      'WG...B...GW',
      'WWJWWVWWQWW',
      'W..bW.W.v.W',
      'WG.GW.WG.GW',
      'WWWWW.WWWWW',
      'W*F.G.G.G.W',
      'WWWWWXWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Keys match doors by colour and shape' },
      { x: 5, y: 3, text: 'A boulder parked on a door blocks it. Mind where you push' },
    ],
    solution: 'RRRRRRRRDDLLLLLLLDLURRRRRDRRRULLLLLDLLDDRDLLRRULUUURRRRDRRDDDLRRULUULLLLDDDDDLLLLRRRRRRRLLLD',
  },
  {
    id: '1-10',
    name: 'Heart of the Jungle',
    idea: 'Mastery: every Angkor mechanic',
    quota: 16,
    par: 150,
    legend: {
      '1': { floor: 'spikes', meta: { period: 4, offset: 1 } },
      '2': { floor: 'spikes', meta: { period: 4, offset: 2 } },
      '3': { floor: 'spikes', meta: { period: 4, offset: 3 } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH.EGEEBEGW',
      'WEEBEGEEGEW',
      'WGEGEBEEEEW',
      'WFEEEGEGBEW',
      'W*WWWWWWWEW',
      'WG..B..B.EW',
      'WWWWC.WC.EW',
      'W.G..S..G.W',
      'W.WWOWWOWWW',
      'W.P321^.G.W',
      'WWWWWWWWW.W',
      'W..OB.OB..W',
      'W.WWWWWWWWW',
      'W...ERE...W',
      'WWW..B..WWW',
      'WWW.BWB.WWW',
      'WWW.WWW.WWW',
      'WG.O..K..GW',
      'WWWWWDWWWWW',
      'W.G.G.G.GXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 10, text: 'Idols save your progress in long climbs' },
    ],
    solution: 'RRRDDLLLRRRURRRDDLRRUURURDLLLLLLDDLLDUUURRRRRRRRDDDDLD........lT.....ULLLDlT...ULLLLRRRRDDRRRLLLLLLLDDRRRRRRRRDDLLLLLLLLLLDDRRRL........DDDDLLRRRRRRRRLLLLDDLLLRRRRRRR',
  },
  {
    id: '1-S1',
    name: 'Vine Vault',
    secret: true,
    idea: 'Pressure plates and gates',
    quota: 6,
    par: 60,
    legend: {
      p: { floor: 'plate', meta: { ch: 'a' } },
      q: { floor: 'plate', meta: { ch: 'b' } },
      a: { floor: 'gate', meta: { ch: 'a' } },
      b: { floor: 'gate', meta: { ch: 'b' } },
      c: { floor: 'gate', meta: { ch: 'c' } },
      l: { floor: 'lever', meta: { ch: 'c' } },
    },
    map: [
      'WWWWWWWWWWW',
      'W.HB..B..GW',
      'W.WWW.WW.WW',
      'W.W..p.Wq.W',
      'W.WWWWWWWWW',
      'W.WWWWWWWWW',
      'W.aGG.GbGGW',
      'WWWWW.WWWWW',
      'W*c.G...GXW',
      'WWWWWWlWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Plates hold gates open while something heavy sits on them' },
      { x: 6, y: 8, text: 'Walk into a lever to pull it' },
    ],
    solution: 'RRRR..RRRRR..RRLLLLLLLLDDDDDRRRRRLDDRDLLLLLRRRRUURRRRLLLLDDLRRRRR',
  },
  {
    id: '1-S2',
    name: 'Moonlit Shrine',
    secret: true,
    dark: true,
    idea: 'Darkness: remember the lit layout',
    quota: 6,
    par: 75,
    map: [
      'WWWWWWWWWWW',
      'WH.^..W.G.W',
      'W.W.W.W.W.W',
      'W.W.G...W.W',
      'W.WWWWW^W.W',
      'W..G..W...W',
      'WWWWW.WW.WW',
      'W.G^...^G.W',
      'W.WWWWWWW.W',
      'W.WGG.F*W.W',
      'W.WWW.WWW.W',
      'W.^...X...W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 1, y: 1, text: 'The lights fade soon. Memorise the spikes' },
    ],
    solution: 'RRDDRRRRUURLDDLLLLUULLDDDDRRRRDDLLLRRRRRRLLLLLLLDDDDRRRRUULLRRRRLLDDR',
  },
  {
    id: '1-B',
    name: 'Naga Warden',
    boss: true,
    idea: 'Drop boulders on the serpent\'s head',
    quota: 0,
    par: 120,
    reward: 'grapple',
    map: [
      'WWWWWXWWWWW',
      'W.........W',
      'W.B.B.B.B.W',
      'W.E.E.E.E.W',
      'W.........W',
      'W....H....W',
      'W.........W',
      'WLLLLNLLLLW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 5, y: 5, text: 'Watch the glowing column: the Naga strikes where it glows' },
      { x: 5, y: 1, text: 'Drop boulders on its head. Only the arena can hurt it' },
    ],
    solution: 'UURRRDDDLUUULDDDLUUULDDDLUUUULLUDUDUDDRRDDDLUUUUURRU',
  },
];
