// World 2: Falkenstein Keep (GDD 6.3). Fire, levers and patrols.

// Shared map characters for this world.
const KEEP = {
  T: { obj: { t: 'tool', tool: 'torch' } },
  z: { floor: 'brazier', meta: { ch: 'a', lit: false } },
  a: { floor: 'gate', meta: { ch: 'a' } },
  b: { floor: 'gate', meta: { ch: 'b' } },
  l: { floor: 'lever', meta: { ch: 'a' } },
  m: { floor: 'lever', meta: { ch: 'c' } },
  p: { floor: 'plate', meta: { ch: 'b' } },
  '=': { floor: 'bridge', meta: { ch: 'a' } },
  '-': { floor: 'bridge', meta: { ch: 'b' } },
  '+': { floor: 'bridge', meta: { ch: 'c' } },
  '#': { floor: 'bridge', meta: { ch: 'c', inv: true } },
  J: { floor: 'jet', meta: { dir: 'L', period: 4, offset: 0 } },
  K: { floor: 'jet', meta: { dir: 'R', period: 4, offset: 2 } },
  '0': { floor: 'blade', meta: { period: 4, offset: 0 } },
  '1': { floor: 'blade', meta: { period: 4, offset: 1 } },
  '2': { floor: 'blade', meta: { period: 4, offset: 2 } },
  '3': { floor: 'blade', meta: { period: 4, offset: 3 } },
};

export const BAVARIA = [
  {
    id: '2-1',
    name: 'Drawbridge',
    idea: 'Levers and bridges',
    quota: 10,
    par: 72,
    legend: KEEP,
    map: [
      'WWWWWWWWWWW',
      'WH..G.B.G.W',
      'WWWlWWW=W.W',
      'WG........W',
      'WWWW-WWpWWW',
      'W...G.GGF*W',
      'WWmWW+WW#WW',
      'WG.G.GWG.GW',
      'WWWWWWWWXWW',
    ],
    tips: [
      { x: 3, y: 1, text: 'Walk into a lever to pull it. It lowers the drawbridge' },
      { x: 5, y: 1, text: 'A boulder dropped on a plate keeps its bridge down' },
      { x: 2, y: 5, text: 'This lever raises one bridge and lowers the other' },
    ],
    solution: 'RRDRRR...R.RRLDDLLLLLLRRRDDRRRRRLLLLLLLLLLLLLDRRRDDLLLLRRRRUULLLDRRRRRRDDLRRLD',
  },
  {
    id: '2-2',
    name: 'Torchlit Hall',
    idea: 'The fire torch: braziers and crates',
    quota: 8,
    par: 50,
    legend: KEEP,
    map: [
      'WWWzWWWzWWW',
      'WH.T.G.G.GW',
      'WWWWWWWW.WW',
      'WzG.cc.G.zW',
      'WWWWWaWWWWW',
      'W*FG.G.G.GW',
      'WWWWWWWWWXW',
    ],
    tips: [
      { x: 3, y: 1, text: 'The fire torch lights braziers. Face one and use your tool' },
      { x: 6, y: 3, text: 'Crates burn. So does anything else wooden' },
      { x: 5, y: 3, text: 'Light every brazier to open the vault' },
    ],
    solution: 'RRuTRRRRuTRRLDDrTLLlTLlTLLLlTRRRDDLLLLRRRRRRRRD',
  },
  {
    id: '2-3',
    name: 'Rat Cellar',
    idea: 'Rat packs: pen them in with crates',
    quota: 8,
    par: 62,
    legend: KEEP,
    map: [
      'WWWWWWWWWWW',
      'WH...E.GG.W',
      'WWWWW.WWW.W',
      'WG.G.c.G.GW',
      'WWWWW.WWWcW',
      'WG.r.*.rWEW',
      'WWWWWWWWW.W',
      'WX.G.G.G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 4, y: 1, text: 'Rats chase you when you come within three steps' },
      { x: 5, y: 2, text: 'Push the crate down to pen the rats in their den' },
      { x: 9, y: 3, text: 'Burn a crate to open the way' },
    ],
    solution: 'RRRRDDLLLLRRRRUURRRRDDLLLLUUDUD.DTDDUUR.RRRUDTDDDDLLLLLLLL',
  },
  {
    id: '2-4',
    name: 'Armoury',
    idea: 'Armour knights charge when they see you',
    quota: 10,
    par: 85,
    secretExit: 'S1',
    legend: KEEP,
    map: [
      'WWWWWWWWWWW',
      'WH.G.B.G.GW',
      'WWWWWC.WWEW',
      'W*.G.n.G.EW',
      'WWWWWOWWWEW',
      'WF.G...G..W',
      'WYWWWWWWW.W',
      'WX.G.G.G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 6, y: 2, text: 'Knights charge in a straight line when they spot you. Drop a rock on one' },
      { x: 9, y: 3, text: 'Stay out of a knight\'s line of sight until you are ready' },
    ],
    solution: 'RRRRR.RRRRDDLLRRDDLLLLLLRRRRRRDDLLLLLLRRRRRRUUUULLLLRLU.DLLLLLRRRRDDRRRRDDLLLLLLLL',
    secretSolution: 'RRRRR.RRRRDDDDLLLLLLLLD',
  },
  {
    id: '2-5',
    name: 'Belfry Bats',
    idea: 'Bats bounce diagonally off the walls',
    quota: 9,
    par: 88,
    legend: KEEP,
    map: [
      'WWWWWWWWWWW',
      'WH.GB.BG.EW',
      'WWWWEWEWWEW',
      'WG.......EW',
      'WW.x...WWEW',
      'W*F..x...GW',
      'WWG.G.G.GWW',
      'WWWWW.WWWWW',
      'WG.G...G.GW',
      'WWWWWXWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Bats fly corner to corner. Read their bounce before you step in' },
      { x: 4, y: 1, text: 'Dig out a rock\'s support to drop it on a passing bat' },
    ],
    solution: 'RRRRDDDDDLLUUULRDDDRRRRRRURUUUULLRRDDDDLLLDLDDLLLLRLRRRRRRRRLLLLUUUUDLL.LLRRRRDDDD',
  },
  {
    id: '2-6',
    name: 'Pressure Gallery',
    idea: 'Plates held down by boulders',
    quota: 7,
    par: 80,
    legend: {
      ...KEEP,
      p: { floor: 'plate', meta: { ch: 'a' } },
      q: { floor: 'plate', meta: { ch: 'b' } },
    },
    map: [
      'WWWWWWWWWWW',
      'WHGB.B.B.OW',
      'WWWW.W.WW.W',
      'WWWWpWqWW.W',
      'WWWWWWWWW.W',
      'W*GbG.GaG.W',
      'WWWWWWWWW.W',
      'WXG.G.G.G.W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Each plate holds a gate open while a boulder sits on it' },
      { x: 7, y: 1, text: 'The last boulder is needed to cross the pit' },
    ],
    solution: 'RRR.RRR.RRRRRRDDDDLLLLLLLRRRRRRRDDLLLLLLLRRRRRRRUULLLLLLLLRRRRRRRRDDLLLLLLLL',
  },
  {
    id: '2-7',
    name: 'Blade Corridor',
    idea: 'Swinging blades and fire jets',
    quota: 7,
    par: 55,
    legend: KEEP,
    map: [
      'WWWWWWWWWWW',
      'WHGc.....JW',
      'WWWWWWWW.WW',
      'W.G30123..W',
      'W.WWWWWWWWW',
      'W.GG..c..JW',
      'WWWW.WWXWWW',
      'WWWWFWWWWWW',
      'WK.G.G.G.*W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Push the crate ahead of you. It soaks up three blasts of fire' },
      { x: 9, y: 3, text: 'Blades swing in a wave. Walk with it' },
    ],
    solution: 'RLRRRRRRTRDDLLLLLLLDDRRRDDDRRRRRLLLLLLRUUURRRD',
  },
  {
    id: '2-8',
    name: 'Collapsing Tower',
    idea: 'Weak floors crumble behind you',
    quota: 8,
    par: 40,
    secretExit: 'S2',
    legend: KEEP,
    map: [
      'WWWWWWWWWWW',
      'WH_G___G__W',
      'W_WWW_WWW_W',
      'W_G_G_G_G_W',
      'W_WWWWWWW_W',
      'W_G_G*G_G_W',
      'WFWWW_WWW.W',
      'WYWX.G.G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Cracked floors fall away once you step off them. Plan one clean route' },
    ],
    solution: 'RRRRRRRRDDLLLLLLLLDDRRRRRRRRDDLLLLLL',
    secretSolution: 'DDDDDD',
  },
  {
    id: '2-9',
    name: 'Dungeon Maze',
    idea: 'Grapple pulls and one-way traps',
    quota: 7,
    par: 50,
    legend: {
      ...KEEP,
      k: { obj: { t: 'key', color: 'gold' } },
      d: { floor: 'door', meta: { color: 'gold' } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH..WWWWWWW',
      'WWW.WWBWWWW',
      'WG....E.kGW',
      'WG..WWW.GGW',
      'WWWdWWWWWWW',
      'W*F.G.G.GXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 3, y: 2, text: 'Trapped? The grapple pulls a boulder towards you. Pull it clear, then walk round' },
    ],
    solution: 'RRDDLLDURRRRRRDRRULL>TLLLLDDDRRRRRLLLLLLLRRRRRRRR',
  },
  {
    id: '2-10',
    name: 'Baron\'s Chambers',
    idea: 'Mastery: every Falkenstein trick',
    quota: 17,
    par: 125,
    legend: {
      ...KEEP,
      p: { floor: 'plate', meta: { ch: 'b' } },
    },
    map: [
      'WWWzWWWzWWW',
      'WH.G.G.G.GW',
      'WWWWWaWWWWW',
      'W...B.....W',
      'WWWWC.WWWEW',
      'WG...n..GEW',
      'WWWWOWWWW.W',
      'W.GG0123..W',
      'W.WWWWWWWWW',
      'W..c.B.P..W',
      'WWWWWW-WWpW',
      'W.G..G..GWW',
      'WWW_WWWWWWW',
      'W_G_G_G_G_W',
      'W_WWWWWWW_W',
      'WG.G.G.G._W',
      'WWWWWWWFWWW',
      'W...X..*GJW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'The Baron\'s own chambers. Every trick of the keep, one room at a time' },
    ],
    solution: 'RRRRRRRRLLuTLLLLuTRRDDDl>T..DLLLLRRRRRRRLLLLDDLLLDD.RR<TRRRRRRRRRLLDDRRLLLLLLRDDRRRRRRDDLLLLLLLLRRRRRRDDRLLLL',
  },
  {
    id: '2-S1',
    name: 'Alchemist\'s Lab',
    secret: true,
    idea: 'Conveyor belts, reversed by a lever',
    quota: 6,
    par: 45,
    legend: {
      ...KEEP,
      '[': { floor: 'conv', meta: { dir: 'L', ch: 'c' } },
      ']': { floor: 'conv', meta: { dir: 'R', ch: 'c' } },
      g: { floor: 'conv', meta: { dir: 'R', ch: 'c' }, obj: { t: 'gem' } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH..G.GG.mW',
      'WW.WWWWW.WW',
      'WG[[[[[[..W',
      'WmWWW.WWW.W',
      'W*]g]g]g].W',
      'WWWWWWWWWXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 2, text: 'Belts carry you and anything on them. Walking against one gets you nowhere' },
      { x: 8, y: 1, text: 'Levers reverse every belt in the lab' },
    ],
    solution: 'RDDDRRDDLLURRRRUULUULLLLRRRRDDRDDD',
  },
  {
    id: '2-S2',
    name: 'Crypt of Echoes',
    secret: true,
    idea: 'Your echo repeats your steps',
    quota: 6,
    par: 40,
    legend: {
      ...KEEP,
      p: { floor: 'plate', meta: { ch: 'a', all: true } },
      q: { floor: 'plate', meta: { ch: 'b', all: true } },
      e: { enemy: { t: 'echo', dir: 'R', lag: 6 } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH..GpG.G.W',
      'WWWWWWWWWaW',
      'We...p....W',
      'WWWWWWWWW.W',
      'WXG.G.G...W',
      'WWWWWWWFWWW',
      'WWWWWWW*WWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Your echo repeats your steps six moves late. Twin plates need you both' },
    ],
    solution: 'RRRRRLLLRR.RRRRDDDDLLDDUULLLLLL',
  },
  {
    id: '2-B',
    name: 'The Iron Baron',
    boss: true,
    bossType: 'baron',
    idea: 'Make him ram the pillars, then drop a boulder on his helmet',
    quota: 0,
    par: 60,
    reward: 'frost',
    legend: KEEP,
    map: [
      'WWWWWXWWWWW',
      'WH........W',
      'W.B.B.B.B.W',
      'W.E.E.E.E.W',
      'W.........W',
      'W.........W',
      'W....N....W',
      'W.........W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 1, y: 1, text: 'The Baron charges in a straight line. Stand under a pillar and dodge' },
      { x: 1, y: 3, text: 'A stunned Baron cannot dodge a falling boulder' },
    ],
    solution: 'RRDRRUDUDDLLLUURRDDRRR.DDULDUUUDL.LUURRU',
  },
];
