// World 4: Bharat Expedition (GDD 6.5). Built around real heritage sites,
// as inspiration only; Meera Rao joins the expedition.

const BHARAT = {
  a: { floor: 'gate', meta: { ch: 'a' } },
  b: { floor: 'gate', meta: { ch: 'b' } },
  l: { floor: 'lever', meta: { ch: 'a' } },
  m: { floor: 'lever', meta: { ch: 'b' } },
  p: { floor: 'plate', meta: { ch: 'a' } },
  q: { floor: 'plate', meta: { ch: 'b' } },
  w: { floor: 'well', meta: { ch: 'a' } },
  v: { floor: 'well', meta: { ch: 'a', inv: true } },
  g: { floor: 'well', meta: { ch: 'a' }, obj: { t: 'gem' } },
  '1': { enemy: { t: 'cobra', dir: 'R' } },
  '2': { enemy: { t: 'cobra', dir: 'L' } },
  '3': { enemy: { t: 'cobra', dir: 'D' } },
  '4': { enemy: { t: 'cobra', dir: 'U', offset: 1 } },
  K: { floor: 'kolam', meta: { ch: 'a' } },
  '!': { floor: 'switch', meta: { ch: 'a' } },
  '?': { floor: 'switch', meta: { ch: 'b' } },
  '6': { obj: { t: 'mirror', o: '/' } },
  '9': { obj: { t: 'mirror', o: '\\' } },
  '@': { floor: 'lamp', meta: { dir: 'R' } },
  '8': { floor: 'lamp', meta: { dir: 'D' } },
  '7': { floor: 'lamp', meta: { dir: 'U', rotate: 20 } },
  '0': { floor: 'sensor', meta: { ch: 'b', latch: true } },
  T: { obj: { t: 'tool', tool: 'bell' } },
  Q: { obj: { t: 'tool', tool: 'disc' } },
  ';': { floor: 'collapse', meta: { at: 0 } },
  f: { obj: { t: 'fruit' } },
  u: { obj: { t: 'pot' } },
  y: { floor: 'well', meta: { ch: 'a', inv: true }, obj: { t: 'red' } },
};

export const INDIA = [
  {
    id: '4-1',
    name: 'Boulder Bazaar of Hampi',
    idea: 'Drop boulders through the clay-pot stalls',
    quota: 4,
    par: 45,
    legend: BHARAT,
    map: [
      'WWWWWWWWWWW',
      'WH.B.B.B.GW',
      'W.WW.W.W.WW',
      'W.WW.W.W.WW',
      'W.WW.W.W.WW',
      'W..GuGuGu*W',
      'WWWWOWOWOXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Clay pots block the bazaar street. Only a falling boulder breaks one' },
    ],
    solution: 'DDDDRRLLUUUURR.RDDDDRLUUUURR.R.RRLDDDDLRRD',
  },
  {
    id: '4-2',
    name: 'The Stepwell',
    idea: 'A lever raises one side of the well and drains the other',
    quota: 5,
    par: 50,
    legend: BHARAT,
    map: [
      'WWWWWlWWWWW',
      'WH........W',
      'WW.WWWWW.WW',
      'WGwwwWvvvGW',
      'WWWWwWvWWWW',
      'WGwgw.vyvGW',
      'WWWWWXWWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 4, y: 1, text: 'The lever floods one side of the stepwell and drains the other' },
    ],
    solution: 'RDDLRRRDDLLLRRRUULLUURRRURRRDDRLLLDDRRRLLLLD',
  },
  {
    id: '4-3',
    name: 'Temple Bells',
    idea: 'The Nandi bell freezes every enemy for three beats',
    quota: 6,
    par: 35,
    legend: BHARAT,
    map: [
      'WWWWWWWWWWW',
      'WHT..G....W',
      'WWWWWWWWW.W',
      'W1...*..G.W',
      'WW.WWWWWWWW',
      'WG.G.G.G.2W',
      'WWWWWWWWXWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Cobras spit three tiles every third beat. Ring the Nandi bell to freeze them' },
    ],
    solution: 'RRRRRRRRDDLLLLLLTLDDLRRRRRRRD',
  },
  {
    id: '4-4',
    name: 'Desert Fort',
    idea: 'The sand floor gives way once the alarm plate is pressed',
    quota: 6,
    par: 34,
    secretExit: 'S1',
    legend: {
      ...BHARAT,
      c: { floor: 'collapse', meta: { ch: 'a', at: 4 } },
      d: { floor: 'collapse', meta: { ch: 'a', at: 5 } },
      e: { floor: 'collapse', meta: { ch: 'a', at: 6 } },
      i: { floor: 'collapse', meta: { ch: 'a', at: 7 } },
      j: { floor: 'collapse', meta: { ch: 'a', at: 8 } },
      k: { floor: 'collapse', meta: { ch: 'a', at: 9 } },
      n: { floor: 'collapse', meta: { ch: 'a', at: 10 } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH.G.G.G.pW',
      'WWWWWWWWW.W',
      'W*.nkjiedcW',
      'WW.WWWWWWWW',
      'WYF.G.G.G2W',
      'WWWWWWWWXWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 9, y: 1, text: 'An alarm plate. Once pressed, the fort floor starts to crumble' },
    ],
    solution: 'RRRRRRRRDDLLLLLLLLRDDRRRRRRD',
    secretSolution: 'RRRRRRRRDDLLLLLLLLRDDL',
  },
  {
    id: '4-5',
    name: 'Monkey Temple',
    idea: 'A langur copies every sidestep in mirror image',
    quota: 6,
    par: 32,
    legend: BHARAT,
    map: [
      'WWWWWWWWWWW',
      'Wz..p.WG.HW',
      'WWWWWWWWW.W',
      'W*G.....G.W',
      'WWWaWWWWWWW',
      'WG..G..G.XW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 8, y: 1, text: 'The langur mirrors your steps: you go left, it goes right. Walls stop it, not you' },
      { x: 4, y: 3, text: 'Get the langur onto the plate while you stand right above the gate' },
    ],
    solution: 'LLRRDDLLLLLLLLRRDDRLLLRRRRRRRR',
  },
  {
    id: '4-6',
    name: 'Monsoon Backwaters',
    idea: 'The river current carries anything set on it; a lever turns the tide',
    quota: 5,
    par: 34,
    legend: {
      ...BHARAT,
      ']': { floor: 'conv', meta: { dir: 'R', ch: 'a' } },
      k: { floor: 'conv', meta: { dir: 'R', ch: 'a' }, obj: { t: 'gem' } },
    },
    map: [
      'WWWWWWWWWWW',
      'Wl......BHW',
      'W~k]]]]]WWW',
      'W.WWWWWWWWW',
      'WG.G*G..GXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 7, y: 1, text: 'The monsoon current carries rocks and gems. Gems will not float over the water' },
      { x: 2, y: 1, text: 'This lever turns the tide' },
    ],
    solution: 'LLL.DULLLLLLRR.DLDDRRRRRRRR',
  },
  {
    id: '4-7',
    name: 'Caves of Ellora',
    idea: 'Carve through soft rock to drop boulders on the cave cobras',
    quota: 6,
    par: 48,
    legend: BHARAT,
    map: [
      'WWWWWWWWWWW',
      'WH.CG.B..GW',
      'WWWWW.CW.WW',
      'WG*...2.G.W',
      'WWCWWWWWC.W',
      'W.G...1.GXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Cracked rock: carve it with the hammer' },
      { x: 5, y: 2, text: 'Carve the rock under the boulder to drop it on the cobra' },
    ],
    solution: 'R.>TRRRDrTDLLLLRdTDDUURRRRTRRUURLDD.TDDR',
  },
  {
    id: '4-8',
    name: 'Sun Chariot',
    idea: 'The chariot-wheel lamp turns with the hours; catch its light',
    quota: 6,
    par: 60,
    secretExit: 'S2',
    legend: {
      ...BHARAT,
      '7': { floor: 'lamp', meta: { dir: 'U', rotate: 6 } },
      '5': { floor: 'sensor', meta: { ch: 'c', latch: true } },
      c: { floor: 'gate', meta: { ch: 'c' } },
    },
    map: [
      'WWWWWWWWWWW',
      'WH..G...G.W',
      'W.WWWWWWW.W',
      'W..6.....5W',
      'W.0.......W',
      'WG6..7..G.W',
      'WWWW...WWcW',
      'WYbG.G*WWXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 1, y: 3, text: 'The sun wheel turns every few beats. Bend its light onto the sensors' },
      { x: 3, y: 4, text: 'Your mirror tool turns a mirror where it stands' },
    ],
    solution: 'RRRRRRRLLLLLLLDDRRRDDL<TUULLDDRRURRRDRRLLDDLLLRRRUURRRDD',
    secretSolution: 'RRRRRRRLLLLLLLDDRRRDDL<TUULLDD.......UURRDDRDDLLL',
  },
];
