// World 3: Monastery of Nine Winds (GDD 6.4). Ice sliding and light.

const MONASTERY = {
  a: { floor: 'gate', meta: { ch: 'a' } },
  b: { floor: 'gate', meta: { ch: 'b' } },
  l: { floor: 'lever', meta: { ch: 'a' } },
  m: { floor: 'lever', meta: { ch: 'b' } },
  p: { floor: 'plate', meta: { ch: 'a' } },
  c: { floor: 'gate', meta: { ch: 'a', inv: true } },
  d: { floor: 'gate', meta: { ch: 'b', inv: true } },
  V: { floor: 'vent', meta: { period: 5, offset: 0 } },
  v: { floor: 'vent', meta: { period: 5, offset: 2 } },
  '<': { floor: 'wind', meta: { dir: 'L' } },
  '>': { floor: 'wind', meta: { dir: 'R' } },
  '{': { floor: 'wind', meta: { dir: 'U' } },
  '}': { floor: 'wind', meta: { dir: 'D' } },
  g: { floor: 'ice', obj: { t: 'gem' } },
  k: { floor: 'ice', obj: { t: 'boulder' } },
  q: { floor: 'ice', obj: { t: 'red' } },
  J: { floor: 'water', enemy: { t: 'spirit', dir: 'L' } },
  K: { floor: 'water', enemy: { t: 'spirit', dir: 'D' } },
  L: { floor: 'water', enemy: { t: 'spirit', dir: 'L' } },
  Q: { obj: { t: 'tool', tool: 'gauntlet' } },
  '@': { floor: 'lamp', meta: { dir: 'R' } },
  '0': { floor: 'sensor', meta: { ch: 'a' } },
  '5': { floor: 'sensor', meta: { ch: 'b', latch: true } },
  C: { obj: { t: 'crate' } },
  '8': { floor: 'lamp', meta: { dir: 'D' } },
  '6': { obj: { t: 'mirror', o: '/' } },
  '9': { obj: { t: 'mirror', o: '\\' } },
};

export const TIBET = [
  {
    id: '3-1',
    name: 'Snow Pass',
    idea: 'Ice: you slide until something stops you',
    quota: 4,
    par: 16,
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WIII.HWWIIW',
      'W.IIIWIgIqW',
      'WI.III.WIWW',
      'WIIIWIIIIIW',
      'WIWgIW...IW',
      'WIIWgIgIIWW',
      'WWWWXWWWWWW',
    ],
    tips: [
      { x: 5, y: 1, text: 'On ice you keep sliding until something stops you. Rocks and dry patches make brakes' },
    ],
    solution: 'LDUURUUURUUULUUUDDUDULUUUULURUDU',
  },
  {
    id: '3-2',
    name: 'Frozen Lake',
    idea: 'The frost charm: freeze water to cross it',
    quota: 4,
    par: 26,
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WH.~.G.~.GW',
      'WWWWWWWWW~W',
      'W*.~~.G.~.W',
      'W~WWWWWWWWW',
      'W.~.G.~~.XW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Face the water and use the frost charm. The ice lasts ten beats' },
      { x: 9, y: 3, text: 'Frozen water is still ice: you slide on it' },
    ],
    solution: 'RrTRRRRrTRRRdTD.lTL.LLlTL.lTL.LdTD.rTR.RRrTR.rTR.R',
  },
  {
    id: '3-3',
    name: 'Prayer Wheel Hall',
    idea: 'Prayer wheels swing gates open and shut',
    quota: 6,
    par: 70,
    legend: MONASTERY,
    map: [
      'WWWlWWWmWWW',
      'WH........W',
      'WWWaWcWWbWW',
      'W*F.WG.WGGW',
      'WWWWWWdWWWW',
      'WG.G.G.G.XW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Each prayer wheel opens some gates and closes others. Plan the order' },
    ],
    solution: 'RRRRDDRDDLLLLLRRRRRRLUULUURRURDDRLUULLLLLUDDLLRRUUURRRRULLDDRDDRRR',
  },
  {
    id: '3-4',
    name: 'Yeti Den',
    idea: 'Yeti cubs slide at you when you line up',
    quota: 7,
    par: 70,
    secretExit: 'S1',
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WH...G..G.W',
      'WWWW.WWWW.W',
      'WG.yO..G.GW',
      'WWWWWW.WWWW',
      'WGO..y...*W',
      'WWWWW.WWWWW',
      'WYF..G..GXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 4, y: 2, text: 'Yeti cubs slide straight at you. Step aside and let them skid into a pit' },
    ],
    solution: 'RRRRRRRRDDLLLLLLLLRRRRRDDU.DLDDRRRLLLUUDUD.ULLLLRRRRRRRRLLLLDDRRRR',
    secretSolution: 'RRRRRRRRDDLLLDDU.DLDDLLLL',
  },
  {
    id: '3-5',
    name: 'Avalanche Chute',
    idea: 'Avalanches pour down the columns',
    quota: 7,
    par: 75,
    legend: MONASTERY,
    map: [
      'WWWVWWWvWWW',
      'WH..G...G.W',
      'WWW.W.W.WWW',
      'WG.......GW',
      'WWW.W.W.WWW',
      'WG.......GW',
      'WWW.W.W.WWW',
      'W*G.....GXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Snowflakes drift down just before a vent lets go. Cross between falls' },
    ],
    solution: 'RRRRRRR.LDDRRL.LDDRRL.LDDRLLLL.LLRRRUULLLLRLRRRRUUL.LLLR.RDDDDLLR.RRRRRRR',
  },
  {
    id: '3-6',
    name: 'Gauntlet Trial',
    idea: 'The power gauntlet: shove two blocks at once',
    quota: 4,
    par: 45,
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WHQ.BB.OO*W',
      'WWWWWWWWW.W',
      'WGO.IIIkI.W',
      'WWWWWWWWW.W',
      'WX.G.G.G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'The power gauntlet pushes two blocks in a row, with no lean' },
      { x: 9, y: 3, text: 'Rocks shoved across ice slide until they reach dry ground' },
    ],
    solution: 'RRRRRRRRDDDDLLLLLLRRRRRRUULULUUUULLLRRRUUUUUDDLLLLLLLL',
  },
  {
    id: '3-7',
    name: 'Spirit Bridges',
    idea: 'Ice spirits freeze the water they pass over',
    quota: 5,
    par: 45,
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WH.G....G.W',
      'WWWWWWWWW.W',
      'WW~~~~~~J.W',
      'WW~WWWWWWWW',
      'W*~~~~~~~WW',
      'WWWWWWWW~WW',
      'WG.G.G.G.XW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Ice spirits drift down the channels, freezing a bridge behind them' },
    ],
    solution: 'RRRRRRRLLRRRDDLUUUUUUUDUURUUUUUUDULLLLLLLRRRRRRRUUULUUUUUURUUUUUUUDUR',
  },
  {
    id: '3-8',
    name: 'Wind Terraces',
    idea: 'Gusts shove you one tile a beat',
    quota: 7,
    par: 35,
    secretExit: 'S2',
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WH.>>>>..GW',
      'WWWWWWW}WWW',
      'WG.<<<..G.W',
      'WW}WWWWWW.W',
      'WG.>>>>>..W',
      'WW}WWWWWWFW',
      'WG..G*G..YW',
      'WWWWWWWXWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Wind pushes you along. Walking against it is slow going' },
    ],
    solution: 'RRRRRRLLDRLLLLLRDLRDLRRRRRRD',
    secretSolution: 'RRRRDRRDDDD',
  },
  {
    id: '3-9',
    name: 'Hall of Mirrors',
    idea: 'Mirrors bend light into sun sensors',
    quota: 5,
    par: 60,
    legend: MONASTERY,
    map: [
      'WWWWW0WWWWW',
      'WH.G...G..W',
      'WWWWW.WWW.W',
      '@......6..W',
      'WW.WWWWWW.W',
      '@.....9...W',
      'WWWWWWWW.aW',
      'WX.G.G.*.GW',
      'WWWWWWWW0WW',
    ],
    tips: [
      { x: 8, y: 3, text: 'Push the mirrors into the sunlight. Every sensor must glow at once' },
      { x: 2, y: 3, text: 'You cast a shadow. Step out of the beam when it is ready' },
    ],
    solution: 'RRRRDDLLLDDRRRRRLLLLLUURRRUURRRRDDLLLRRRDDDDLLLLLLLL',
  },
  {
    id: '3-10',
    name: 'Summit of the Winds',
    idea: 'Mastery: ice, avalanches, wind and light',
    quota: 9,
    par: 70,
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WHIII.WII.W',
      'WgIWIIIg.IW',
      'WWI.IIIWIIW',
      'WIWIWIIII.W',
      'WIIIIIWI.IW',
      'WWWVWvW.WWW',
      'WG....G..GW',
      'WWW.W.W.WWW',
      'W*.......GW',
      'WW}WWWWW8WW',
      'W.G.....C.W',
      'WWWWWWWb5WW',
      'WX.G.G...GW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 11, text: 'Sunlight on the sensor opens the summit gate for good' },
    ],
    solution: 'DURUDURRUUUUURUDUULUDDDDRRLLUURRLLLLLLLLRRDDLLRD.RRRRR<<rTDDRRLLLLLLLL',
  },
  {
    id: '3-S1',
    name: 'Hot Spring Caves',
    secret: true,
    idea: 'Melt ice with the torch, refreeze it with the charm',
    quota: 4,
    par: 30,
    legend: MONASTERY,
    map: [
      'WWWWWWWWWWW',
      'WH.IIIII~GW',
      'W.WWWWWWWWW',
      'W.~IIIIIIGW',
      'W.WWWWWWWWW',
      'WG.III~II*W',
      'WWWWW.WWWWW',
      'WG.IIIIIIIW',
      'WWWWWWWWWXW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Water stops a slide. The frost charm turns it to ice, the torch turns ice back to water' },
    ],
    solution: 'RR.....<rTR.L.......LDDrTR.......L.......lTL.DDRR...<lT>rTR....L....DD.L...LRR.......D',
  },
  {
    id: '3-S2',
    name: 'Sky Burial Peak',
    secret: true,
    idea: 'Gusts and falling snow on the high ridge',
    quota: 6,
    par: 60,
    legend: MONASTERY,
    map: [
      'WWWWVWWWvWW',
      'WH.>>...<.W',
      'WW}WWWWW{WW',
      'WG.>>>...GW',
      'WWWWWWW}WWW',
      'W*<<<<<..GW',
      'W.W}WWWWWWW',
      'WG.G...G.XW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'High winds and snow. Read both before you step' },
    ],
    solution: 'RDLRRRRRRLLDRRLLLLDLLRRRRRRLLLLLLUUDDRRRRRRRR',
  },
  {
    id: '3-B',
    name: 'Frostfang',
    boss: true,
    bossType: 'frost',
    idea: 'Slide boulders across the ice into the guardian',
    quota: 0,
    par: 60,
    reward: 'mirror',
    legend: MONASTERY,
    map: [
      'WWWWWXWWWWW',
      'WH........W',
      'W.WWWWWWW=W',
      'W.BIIIIII=W',
      'W.WWWWWWW=W',
      'W.BIIIIIINW',
      'W.WWWWWWW=W',
      'W.BIIIIII=W',
      'WWWWWWWWW=W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 1, y: 1, text: 'Frostfang breathes along its row. Never stand level with it when it inhales' },
      { x: 1, y: 3, text: 'Shove a boulder down the ice when Frostfang is at the end of that lane' },
    ],
    solution: 'DDDDDDRLUUUUUDDD.RLUUUUDDRLUUDUDDRLUUDUDDDDRLDUUUUURRRRU',
  },
];
