// World 5: The Obsidian Vault (GDD 6.6). The syndicate's vault beneath
// the four temples: every tool is in hand and each stage remixes two
// worlds, ending with lethal lasers, echoes, a collapse and the Hand.

const VAULT = {
  a: { floor: 'gate', meta: { ch: 'a' } },
  b: { floor: 'gate', meta: { ch: 'b' } },
  l: { floor: 'lever', meta: { ch: 'a' } },
  m: { floor: 'lever', meta: { ch: 'b' } },
  p: { floor: 'plate', meta: { ch: 'a' } },
  q: { floor: 'plate', meta: { ch: 'b' } },
  z: { floor: 'brazier', meta: { ch: 'a', lit: false } },
  '=': { floor: 'bridge', meta: { ch: 'a' } },
  '-': { floor: 'bridge', meta: { ch: 'b' } },
  '@': { floor: 'lamp', meta: { dir: 'R', laser: true } },
  '8': { floor: 'lamp', meta: { dir: 'D', laser: true } },
  '4': { floor: 'lamp', meta: { dir: 'L', laser: true } },
  '7': { floor: 'lamp', meta: { dir: 'U', laser: true } },
  '$': { floor: 'lamp', meta: { dir: 'R' } },
  '6': { obj: { t: 'mirror', o: '/' } },
  '9': { obj: { t: 'mirror', o: '\\' } },
  '0': { floor: 'sensor', meta: { ch: 'a', latch: true } },
  '5': { floor: 'sensor', meta: { ch: 'b', latch: true } },
  '!': { floor: 'switch', meta: { ch: 'a' } },
  '?': { floor: 'switch', meta: { ch: 'b' } },
  w: { floor: 'well', meta: { ch: 'a' } },
  v: { floor: 'well', meta: { ch: 'a', inv: true } },
  g: { floor: 'ice', obj: { t: 'gem' } },
  k: { floor: 'ice', obj: { t: 'boulder' } },
  h: { obj: { t: 'heart' } },
  s: { floor: 'plate', meta: { ch: 'a', only: 'heart', all: true } },
  J: { floor: 'jet', meta: { dir: 'L', period: 4, offset: 0 } },
  K: { floor: 'jet', meta: { dir: 'R', period: 4, offset: 2 } },
  '1': { enemy: { t: 'cobra', dir: 'R' } },
  '2': { enemy: { t: 'cobra', dir: 'L' } },
};

export const VAULT_LEVELS = [
  {
    id: '5-1',
    name: 'Breach',
    idea: 'Roots and levers: dig into the vault the old way',
    quota: 4,
    par: 55,
    legend: VAULT,
    map: [
      'WWWWWWWWWWW',
      'WHEEGEEEElW',
      'WEWWWWWWWWW',
      'WEEGEEEaG*W',
      'WWWWWWWWWEW',
      'WX.GOB.EEEW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 1, y: 1, text: 'The vault was built into the old temple roots. Dig, drop and pull' },
    ],
    solution: 'RRRLLLDDRRLLUURRRRRRRRLLLLLLLDDRRRRRRRRDDLLLLLLLL',
  },
  {
    id: '5-2',
    name: 'Cold Storage',
    idea: 'Fire and ice: light the brazier, then freeze your own bridge',
    quota: 5,
    par: 30,
    legend: VAULT,
    map: [
      'WWWWWzWWWWW',
      'WH.G...G..W',
      'WWWWWWWWaWW',
      'WgIIIIIII.W',
      'WWWWWWWWW.W',
      'WX.G~..G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 4, y: 1, text: 'Every tool is yours now. Cycle to the torch and light the brazier above' },
      { x: 6, y: 5, text: 'The frost charm turns water to ice for a short while' },
    ],
    solution: 'RRRRu>>>TRRRDDL......LR........RUUUUUUUDDLLLL>TLLLL',
  },
  {
    id: '5-3',
    name: 'Heat Exchange',
    idea: 'Light and water: sunlight passes through the cistern to its sensor',
    quota: 3,
    par: 25,
    legend: VAULT,
    map: [
      'WWWWWWWWWWW',
      'W$.H6WWWWWW',
      'WW.W~WWWWWW',
      'WW.W~WWWWWW',
      'WW.W0WWWWWW',
      'WGG.~a*G.XW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 3, y: 1, text: 'Turn the mirror so the sunlight falls down the cistern' },
    ],
    solution: 'r<<TLDDDDLRRr<<TRRRRRR',
  },
  {
    id: '5-4',
    name: 'Vault Gardens',
    idea: 'Stepwells and thickets: burn a way in, then play the tide',
    quota: 6,
    par: 50,
    legend: VAULT,
    map: [
      'WWWWWlWWWWW',
      'WH.c......W',
      'WW.WWWWW.WW',
      'WGwwwWvvvGW',
      'WWWWwWvWWWW',
      'WGwGw.vGvGW',
      'WWWWWXWWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'A thicket of vines. Your torch clears it' },
      { x: 5, y: 1, text: 'The lever floods one garden well and drains the other' },
    ],
    solution: 'Rr>>>TDDLRRRDDLLLRRRUULLUURRRURRRDDRLLLDDRRRLLLLD',
  },
  {
    id: '5-5',
    name: 'Laser Grid',
    idea: 'Red lasers burn; crates make shields',
    quota: 5,
    par: 40,
    legend: VAULT,
    map: [
      'WWWWWWWWWWW',
      'WH......GGW',
      'W@..c...WWW',
      'WWW.WWWWWWW',
      'WG.....c.4W',
      'WWWWWWW.WWW',
      'WX*..G.G..W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 5, y: 1, text: 'Lasers burn. Keep a crate between you and the emitter' },
    ],
    solution: 'RRRRRRRRLLDLLLLDDLLRRRRRRDDLLLLLL',
  },
  {
    id: '5-6',
    name: 'Echo Chamber',
    idea: 'Your echo repeats your moves six steps late',
    quota: 3,
    par: 30,
    legend: VAULT,
    map: [
      'WWWWWWWWWWW',
      'We..pWHG..W',
      'WWWWWWWWW.W',
      'W.G*.a..G.W',
      'WXWWWWWWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 6, y: 1, text: 'The echo copies every step you take, six steps late. Walls stop it; they do not stop you' },
      { x: 6, y: 3, text: 'Only the echo can hold the plate for you' },
    ],
    solution: 'RRRDDLLLRLLLLLLD',
  },
  {
    id: '5-7',
    name: 'Freight Lift',
    idea: 'Freight belts deliver crates and boulders where you need them',
    quota: 3,
    par: 28,
    legend: VAULT,
    map: [
      'WWWWWWWWWWW',
      'WHGc)))))pW',
      'WWWWWWaWWWW',
      'WGO((B.*.GW',
      'WXWWWWWWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Freight belts carry anything set on them. Send the crate to the plate' },
    ],
    solution: 'RRLRRL.DDRRRLLLLLLLD',
  },
  {
    id: '5-8',
    name: 'Collapse',
    idea: 'The alarm drops the vault floor behind you. Run, and grab what you can',
    quota: 4,
    par: 25,
    legend: {
      ...VAULT,
      c: { floor: 'collapse', meta: { ch: 'a', at: 3 } },
      d: { floor: 'collapse', meta: { ch: 'a', at: 5 } },
      e: { floor: 'collapse', meta: { ch: 'a', at: 6 } },
      f: { floor: 'collapse', meta: { ch: 'a', at: 9 } },
      i: { floor: 'collapse', meta: { ch: 'a', at: 10 } },
      j: { floor: 'collapse', meta: { ch: 'a', at: 11 } },
      k: { floor: 'collapse', meta: { ch: 'a', at: 16 } },
      n: { floor: 'collapse', meta: { ch: 'a', at: 17 } },
    },
    map: [
      'WWWWWWWWWWW',
      'WHcdefGjkGW',
      'WpcdefWjkWW',
      'W.cGefijGnX',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 1, y: 1, text: 'This plate trips the vault alarm. The floor will not wait for you' },
    ],
    solution: 'DRRDRRUURRRRLDDRR',
  },
  {
    id: '5-9',
    name: 'The Lattice',
    idea: 'Slide the four Heart Stones into the Star Lattice',
    quota: 3,
    par: 55,
    legend: VAULT,
    map: [
      'WWWWWWWWWWW',
      'W....H....W',
      'W.h..s..h.W',
      'W.........W',
      'W..s.h.s..W',
      'W.........W',
      'W.h..s....W',
      'WWWWWWWWWaW',
      'WX*G..G.G.W',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 5, y: 1, text: 'Each Heart Stone fits any socket. All four must sit in the lattice at once' },
    ],
    solution: 'LLLLDRRRURRRRRDLULDDLDLLDLLLDRRRURRRRRDDDLLLLLLLL',
  },
  {
    id: '5-10',
    name: 'Heart of the Hand',
    idea: 'The syndicate\'s guards give chase. Lead them into the laser',
    quota: 3,
    par: 65,
    legend: {
      ...VAULT,
      '>': { floor: 'lamp', meta: { dir: 'R', laser: true, ch: 'a' } },
    },
    map: [
      'WWWWWlWWWWW',
      'WH........W',
      'W.WWWWWWW.W',
      '>.........W',
      'W.WWWWWWW.W',
      'WG.u.G.u.GW',
      'WWWWWXWWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 1, text: 'Obsidian Hand guards hunt you down. The lever powers the laser corridor' },
    ],
    solution: 'DDDDUURRRRRRRRUULLLLUURRRRDDDDUULLLLLLLLUURRRRUULLLLDDDDRRRRD',
  },
  {
    id: '5-B',
    name: 'The Obsidian Hand',
    boss: true,
    bossType: 'hand',
    idea: 'He mirrors every step you take. Walk him into his own lasers',
    quota: 0,
    par: 30,
    legend: {
      ...VAULT,
      '<': { floor: 'lamp', meta: { dir: 'L', laser: true, ch: 'a' } },
      '[': { floor: 'lamp', meta: { dir: 'L', laser: true, ch: 'b' } },
    },
    map: [
      'WWWWWWWWWWW',
      'W....WWWWWW',
      'W^...W....<',
      'l....m....W',
      'W^...W..N.[',
      'W.H..WWWWWW',
      'WWWXWWWWWWW',
      'WWWWWWWWWWW',
    ],
    tips: [
      { x: 2, y: 5, text: 'He copies your steps, left for right. Walls stop him; they do not stop you' },
      { x: 1, y: 3, text: 'Each lever powers one of his lasers' },
    ],
    solution: 'UULLURUDDUUDUDUDUDDDDRD',
  },
];
